{
    'name': 'Freight Management',
    'version': '15.0.1.0.0',
    'summary': 'Module for Managing All Freight Operations',
    'description': 'Module for Managing All Freight Operations',
    'author': 'Invincix',
    'maintainer': 'Invincix',
    'company': 'Invincix',
    'website': "https://www.invincix.com/",
    'depends': ['base', 'base_address_city', 'account'],
    'data': [
        'security/ir.model.access.csv',
        'views/menu_views.xml',
        'views/area_views.xml',
        'views/division_views.xml',
        'views/district_views.xml',
        'views/delivery_type_views.xml',
        'views/commodity_views.xml',
        'views/payment_term_views.xml',
        'views/shipping_line.xml',
        'views/vessel_code.xml',
        'views/port_info.xml',
        'views/cargo_class.xml',
        'views/container_type.xml',

    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}
